export const EXAMPLE = {
  GET: {
    START: 'EXAMPLE/GET/START',
    SUCCESS: 'EXAMPLE/GET/SUCCESS',
    ERROR: 'EXAMPLE/GET/ERROR',
  },
  REMOVE: {
    START: 'EXAMPLE/REMOVE/START',
    SUCCESS: 'EXAMPLE/REMOVE/SUCCESS',
    ERROR: 'EXAMPLE/REMOVE/ERROR',
  }
};

export default {
  EXAMPLE,
};
